server:
  port: 8010
  tomcat:
    max-connections: 512
    max-threads: 512
    uri-encoding: utf-8

spring:
  application:
    name: boot-consul
  profiles:
    active: dev

logging:
  config: classpath:logback-spring.xml
  path: ./logs

log:
  root:
    level: INFO
